FreeTransfer/urls.py
from django.conf import settings
from django.conf.urls.static import static

# FreeTransfer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from . import views
from django.contrib.auth import views as views_django
from django.contrib.auth import authenticate, login as login_django
from django.contrib.auth.views import LoginView
from transacciones.views import MotivoDeleteView,MotivoCreateView,ingresar_dinero,realizar_transferencia

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('login/', views_django.LoginView.as_view(template_name="login.html"), name='login'),
    path('accounts/login/registro/', views.registro, name='registro'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registro/', views.registro, name='registro'),


    # Incluir las rutas de la app transacciones
    path('transacciones/', include('transacciones.urls')),
    path('usuarios/', include('usuarios.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transacciones/urls.py
# movimientos/urls.py
from django.urls import path
from . import views
from transacciones.views import MotivoDeleteView,MotivoCreateView,ingresar_dinero,realizar_transferencia
from usuarios.views import agregar_favorito


app_name = 'transacciones'
urlpatterns = [
    #path('', views.home, name='home'),
    path('ingresar_dinero/', views.ingresar_dinero, name='ingresar_dinero'),
    # transferencia con username como parametro
    path('realizar_transferencia/<str:destinatario_username>/', views.realizar_transferencia, name='realizar_transferencia'),
    path('realizar_transferencia/', views.realizar_transferencia, name='realizar_transferencia'),
    path('confirmacion_transferencia/', views.confirmacion_transferencia, name='confirmacion_transferencia'),
    path('usuarionovalido/', views.realizar_transferencia, name='destinatario_novalido'),
    path('saldoinsuficiente/', views.realizar_transferencia, name='saldoinsuficiente'),
    path('listar_movimientos/', views.listar_movimientos ,name='listar_movimientos'),
    path('listar_motivos/', views.listar_motivos,name='listar_motivos'),
    path('Modificar/<str:pk>', views.ModificarMotivo.as_view(template_name= "modificar_motivo.html"), name='modificar_motivo' ),
    path('eliminar/<int:pk>/',MotivoDeleteView.as_view(), name='eliminar_motivo'),
    path('crear/', MotivoCreateView.as_view(), name='crear_motivo'),
    path('movimientos/favorito/<int:cuenta_destino_id>/', agregar_favorito, name='agregar_favorito'),




    #path('realizar_transferencia/', views.realizar_transferencia, name='realizar_transferencia'),
]

usuarios/urls.py
from django.urls import path

from . import views
from .views import UsuarioDeleteView, EditarPerfilView


app_name = 'usuarios'

urlpatterns = [
    #path('transferencia/', views.transferencia, name='transferencia'),
    path('ingresar_dinero/', views.ingresar_dinero, name='ingresar_dinero'),
    path('ingresar_dinero/confirmacion', views.confirmacion, name='ingresar_dinero'),
    path('realizar_transferencia/', views.realizar_transferencia, name='realizar_transferencia'),
    path('realizar_transferencia/ingresar_monto_transferencia/', views.ingresar_monto_transferencia, name='ingresar_monto_transferencia'),
   	path('realizar_transferencia/ingresar_monto_transferencia/confirmacion', views.confirmacion, name='confirmar_transferencia'),  # Página de confirmación
    path('confirmacion/', views.confirmacion, name='confirmacion'),
    path('tudinero', views.tudinero, name='tudinero'),
    path('tuactividad', views.tuactividad, name='tuactividad'),
    # path('login/', views_django.LoginView.as_view(template_name="login.html"), name='login'),
    path('favoritos/', views.Listar.as_view(), name='favoritos'),
    # eliminar fav
    path('eliminar_favorito/<int:usuario_favorito_id>/', views.eliminar_favorito, name='eliminar_favorito'),
    # detalle vacuna
    path('usuario/<int:pk>/', views.UsuarioPerfil.as_view(), name='perfil'),
    path('perfil/editar/', EditarPerfilView.as_view(), name='editar_perfil'),

    path('eliminar/<int:pk>/',UsuarioDeleteView.as_view(), name='eliminar_usuario'),
    path('listado_usuarios/', views.listar_usuarios,name='listado_usuarios'),
    path('movimiento_por_usuario/<int:pk>/', views.Listar_MovimientosPorUsuario,name='movimiento_por_usuario'),
    path('usuariodenegadp/', views.Listar_MovimientosPorUsuario, name='usuariodenegadp'),

    #path('editar_perfil/<str:pk>', views.EditarPerfil_clase.as_view(template_name= "editarperfil.html"), name='editar_perfil' ),
    # path('editar_perfil/<str:pk>/', views.EditarPerfil_clase.as_view(), name='editar_perfil'),
    path('activar_usuario/<str:pk>/', views.activar_usuario.as_view(), name='activar_usuario'),
    

]





 

transacciones/models.py
from django.db import models

# Create your models here.
# movimientos/models.py

from django.db import models
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
from usuarios.models import Usuario, MotivoTransferencia



class Cuenta(models.Model):
    saldo = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    usuario= models.OneToOneField(Usuario, related_name = 'usuariocuenta', on_delete=models.CASCADE,null=True, blank=True)


    def __str__(self):
        return f"{self.usuario.username} - ${self.saldo}"


class Movimiento(models.Model):
    TIPO_MOVIMIENTO = [
    ('ingreso', 'Ingreso'),
    ('transferencia', 'Transferencia'),
    ('ingresotransferencia', 'Ingreso  por Transferencia')
]

    cuenta_movimiento=models.ForeignKey(
        Cuenta, on_delete=models.CASCADE, related_name='cuenta', null=True, blank=True
    )
    cuenta_origen = models.ForeignKey(
        Cuenta, on_delete=models.CASCADE, related_name='cuenta_origen', null=True, blank=True
    )
    cuenta_destino = models.ForeignKey(
        Cuenta, on_delete=models.CASCADE, related_name='cuenta_destino', null=True, blank=True
    )
    tipo = models.CharField(max_length=30, choices=TIPO_MOVIMIENTO)
    monto = models.DecimalField(max_digits=10, decimal_places=2)
    motivo = models.ForeignKey(MotivoTransferencia, on_delete=models.SET_NULL, null=True, blank=True)
    fecha = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.tipo} - {self.monto} ({self.cuenta_origen} -> {self.cuenta_destino})"

transacciones/forms.py
# transacciones/forms.py
from django import forms
from django.contrib.auth.models import User

class IngresoDineroForm(forms.Form):
    monto = forms.DecimalField(max_digits=10, decimal_places=2, label="Monto a ingresar")



from .models import MotivoTransferencia

class TransferenciaForm(forms.Form):
    destinatario = forms.CharField(max_length=150, label="Usuario Destinatario")
    monto = forms.DecimalField(max_digits=10, decimal_places=2, label="Monto")
    motivo = forms.ModelChoiceField(
        queryset=MotivoTransferencia.objects.all(),
        label="Motivo de la Transferencia",
        empty_label="Seleccione un motivo"
    )

class ModificacionMotivo(forms.ModelForm):

	class Meta:
		model = MotivoTransferencia
		fields = ['nombre']

transacciones/views.py
from django.shortcuts import render

# Create your views here.
# movimientos/views.py
from django.shortcuts import render, redirect
from .models import Cuenta, MotivoTransferencia, Movimiento
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import TransferenciaForm
from .models import Cuenta
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy


from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Cuenta
# transacciones/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import IngresoDineroForm
from .models import Cuenta
from django.contrib.auth import get_user_model
from .forms import ModificacionMotivo
from django.views.generic.edit import DeleteView 
from django.views.generic.edit import CreateView
from django.http import HttpResponse
User = get_user_model()






#def home(request):
 #   context={}
  #  if request.user.is_authenticated:
        # Intentamos obtener la cuenta asociada al usuario logueado
    #    try:
     #       cuenta = Cuenta.objects.get(usuario=request.user)
      #      context['monto']=cuenta.saldo
       #     saldo=cuenta.saldo
        #except Cuenta.DoesNotExist:
         #   saldo = 0  # Si no existe la cuenta, el saldo será 0
    

    #return render(request, 'home.html', {'saldo': saldo})





def listar_cuentas(request):
    cuentas = Cuenta.objects.all()
    return render(request, 'movimientos/listar_cuentas.html', {'cuentas': cuentas})



@login_required
def ingresar_dinero(request):
    if request.method == 'POST':
        form = IngresoDineroForm(request.POST)
        if form.is_valid():
            monto = form.cleaned_data['monto']
            # Obtener la cuenta del usuario autenticado
            cuenta = Cuenta.objects.get(usuario=request.user)
            cuenta.saldo += monto
            cuenta.save()
            Movimiento.objects.create(cuenta_origen=cuenta, cuenta_movimiento=cuenta, tipo="ingreso", monto=monto)
            return redirect('transacciones:confirmacion_transferencia')  # Redirigir a la página principal o una página de confirmación
    else:
        form = IngresoDineroForm()

        # Guardar el movimiento para historial
    
            

    return render(request, 'ingresar_dinero.html', {'form': form})


@login_required
def realizar_transferencia(request, destinatario_username=None):
    if request.method == 'POST':
        form = TransferenciaForm(request.POST)
        if form.is_valid():
            destinatario_username = form.cleaned_data['destinatario']
            monto = form.cleaned_data['monto']
            motivo = form.cleaned_data['motivo']
            
            # Verificar que el destinatario existe
            try:
                destinatario = User.objects.get(username=destinatario_username)
            except User.DoesNotExist:
                return render(request, 'destinatario_novalido.html', {'form': form})
            if destinatario.is_active == False:
                return render(request, 'destinatario_novalido.html', {'form': form})
            


            # Verificar que el remitente tiene saldo suficiente
            remitente_cuenta, _ = Cuenta.objects.get_or_create(usuario=request.user)
            if remitente_cuenta.saldo < monto:
                return render(request, 'saldoinsuficiente.html', {'form': form})

                # Obtener o crear la cuenta del destinatario
            destinatario_cuenta, _ = Cuenta.objects.get_or_create(usuario=destinatario)

                # Realizar la transferencia
            remitente_cuenta.saldo -= monto
            remitente_cuenta.save()

            destinatario_cuenta.saldo += monto
            destinatario_cuenta.save()

                # Guardar el movimiento para historial
            Movimiento.objects.create(cuenta_origen=remitente_cuenta, cuenta_movimiento=remitente_cuenta,cuenta_destino=destinatario_cuenta, tipo="transferencia", monto=monto, motivo=motivo)
            Movimiento.objects.create(cuenta_origen=remitente_cuenta, cuenta_movimiento=destinatario_cuenta,cuenta_destino=destinatario_cuenta, tipo="ingreso transferencia", monto=monto, motivo=motivo)

                # Redirigir a una página de confirmación
            return redirect('transacciones:confirmacion_transferencia')  # Redirigir a una página de confirmación
            
                
                
                
    else:
        # Si se recibe un destinatario por URL, prefijar el formulario
        initial_data = {'destinatario': destinatario_username} if destinatario_username else {}
        form = TransferenciaForm(initial=initial_data)

    return render(request, 'Transferencia.html', {'form': form})



def confirmacion_transferencia(request):
    return render(request, 'confirmacion_transferencia.html')


def listar_movimientos(request):

    context={}

    cuent= Cuenta.objects.get(usuario=request.user)#busca el objeto cuenta del usuario que esta logueado
    todos= Movimiento.objects.filter(cuenta_movimiento=cuent) # busca todos los movimientos de la cuenta del usuario logueado que buscamos anteriormente
    context['movimientos']=todos #paso todos los movimientos a context para enviar al html
    return render(request,'listado.html', context)

def listar_motivos(request):
    if not request.user.is_staff:
        messages.error(request, "No tienes permisos para acceder a esta página.")
        return render(request, 'usuarios/denegado.html')
    context={}
    todos=MotivoTransferencia.objects.all() #MotivoTransferencia.objects.all()
    context['motivos']=todos
    return render(request,'listado_motivos.html', context)


class ModificarMotivo(UpdateView):
    model = MotivoTransferencia
    form_class = ModificacionMotivo
    template_name = 'transacciones/modificar_motivo.html'
    success_url = reverse_lazy('transacciones:listar_motivos')

    def form_valid(self, form):
        
        motivo = form.save(commit = False)
        motivo.save()

        return redirect(self.success_url)


class MotivoDeleteView(DeleteView):
    model = MotivoTransferencia
    template_name = 'Confirmacion.html'
    success_url = reverse_lazy('transacciones:listar_motivos')  # Redirige tras eliminar


class MotivoCreateView(CreateView):
    model = MotivoTransferencia
    template_name = 'motivo_nuevo.html'  # La plantilla que se usará para el formulario
    fields = ['nombre']  # Campos que estarán disponibles en el formulario
    success_url = reverse_lazy('transacciones:listar_motivos')  # URL a la que se redirige después de la creación

transacciones/templates/Transferencia.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block contenido %}
<main class="container-body">
  <h2>Realizar Transferencia</h2>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Transferir</button>
  </form>
</main>
{% endblock %}

transacciones/templates/confirmacion.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block contenido1 %}
<p>Tickets</p>

{% endblock %}


{% block contenido %}
            <!-- COMIENZO DEL SECTOR DE TARJETAS DE CANTIDAD-->

            
           


<main class="container-body">
  <div id="contenido" class="pages-container-fluid pt-4 pb-4 pl-4 pr-4">
    <div>
      <h4>vista administrador: Modificar Motivo</h4>
      <div id="tarjetas" class="row">
        

      </div>


            <!-- COMIENZO DEL SECTOR DE TABLA DE TICKETS  -->


<div id="contenido"  class="pages-container-fluid pt-2 pb-2 pl-5 pr-5">

  <div class="col-12 col-xl-12 mb-4 align-items-stretch">

    <div class="card h-100 border-0 rounded">

      <div id="tabla" class="row">

        <div _ngcontent-c4="" class="col-sm-12 col-xl-8 mb-4 align-items-stretch">
          
      
      <div _ngcontent-c4="" class="col-sm-12 col-xl-4 mb-4 align-items-stretch">
          
            <div _ngcontent-c4="" class="card-title mb-1 p-3 d-flex">
              <h4>Eliminar:</h4>
              <a _ngcontent-c4="" class="btn ml-auto p-0 text-lightning">
                <i _ngcontent-c4="" class="fas fa-ellipsis-h"></i>
              </a>
            </div>
            <div _ngcontent-c4="" class="card-body">
                <h1>¿Estás seguro de que deseas eliminar el motivo "{{ object.nombre }}"?</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Eliminar</button>
        <a href="% url 'transacciones:listar_motivos' %}">Cancelar</a>
    </form>



            </div>
        
        

     
      </div>
    </div>
    </div>
    </div>
    </div>

  </div>
  

</main>
 

{% endblock %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eliminar Producto</title>
</head>
<body>
    <h1>¿Estás seguro de que deseas eliminar el motivo "{{ object.nombre }}"?</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Eliminar</button>
        <a href="{% url 'producto_list' %}">Cancelar</a>
    </form>
</body>
</html>

transacciones/templates/confirmacion_transferencia.html
{% extends 'base.html' %}
{% block contenido %}
<main class="container-body">
  <div id="contenido" class="pages-container-fluid pt-4 pb-4 pl-4 pr-4">
    <div class="row">
      <div class="col-md-12 mb-4">
        <div class="card border-0 rounded-0 text-center">
          <div class="card-body">
            <h5 class="card-title">Operación realizada con éxito</h5>
            <p class="card-text">Gracias por utilizar FreeTransfer.</p>
            <a href="{% url 'home' %}" class="btn btn-primary">Volver al inicio</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

transacciones/templates/destinatario_novalido.html
{% extends 'base.html' %}
{% block contenido %}
<main class="container-body">
  <div id="contenido" class="pages-container-fluid pt-4 pb-4 pl-4 pr-4">
    <div class="row">
      <div class="col-md-12 mb-4">
        <div class="card border-0 rounded-0 text-center">
          <div class="card-body">
            <h5 class="card-title">Destinatario no valido</h5>
            <p class="card-text">Intente de nuevo por favor.</p>
            <a href="{% url 'transacciones:realizar_transferencia' %}" class="btn btn-primary">Volver a intentar</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

transacciones/templates/ingresar_dinero.html
<!-- templates/transacciones/ingresar_dinero.html -->
{% extends 'base.html' %}

{% block contenido %}
<main class="container-body">
  <div id="contenido" class="pages-container-fluid pt-4 pb-4 pl-4 pr-4">
    <div class="row">
      <!-- Formulario de ingreso de dinero -->
      <div class="col-md-12 mb-4">
        <div class="card border-0 rounded-0">
          <div class="card-title mb-1 p-3">
            <h5>INGRESAR DINERO</h5>
          </div>
          <div class="card-body">
            <form method="POST">
              {% csrf_token %}
              {{ form.as_p }}  <!-- Renderiza el formulario automáticamente -->
              <button type="submit" class="btn btn-primary">Confirmar Ingreso</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

transacciones/templates/listado.html
						<!-- COMIENZO DEL SECTOR DE TARJETAS DE CANTIDAD-->
{% extends 'base.html' %}

{% block contenido1 %}


{% endblock %}

{% block contenido %}


<main class="container-body">
  <div id="contenido" class="pages-container-fluid pt-2 pb-2 pl-5 pr-5">
    <div class="col-12 col-xl-12 mb-4 align-items-stretch">
      <!-- Mensaje de bienvenida con el nombre del usuario o "invitado" si no está logueado -->
      <h4>Bienvenido,{% if user.is_authenticated %}{{ user.username }}{% else %}invitado{% endif %}!</h4>
      
      <!-- Información de la tarjeta -->
      <div class="card">
        
        <div class="card-body">
         
        	<div id="tabla" class="row">

				<div _ngcontent-c4="" class="col-12 col-xl-12 mb-4 align-items-stretch">
					<div _ngcontent-c4="" class="card h-100 border-0 rounded-0">
						<div _ngcontent-c4="" class="card-title mb-1 p-3 d-flex">
							<h5 class="card-header">HISTORIAL DE MOVIMIENTOS DEL USUARIO</h5>
							<a _ngcontent-c4="" class="btn ml-auto p-0 text-lightning">
								<i _ngcontent-c4="" class="fas fa-ellipsis-h"></i>
							</a>
						</div>
						<div _ngcontent-c4="" class="card-body">
							<div _ngcontent-c4="" class="table-responsive-md">
								<div _ngcontent-c4="" class="table-responsive">
									<table _ngcontent-c4="" class="table ">
										<thead _ngcontent-c4="">
											<tr _ngcontent-c4="">
												
												<th _ngcontent-c4="" style="width:10%;">FECHA y HORA</th>
												
												<th _ngcontent-c4="" style="width:15%;">TIPO DE OPERACION</th>
												<th _ngcontent-c4="" class="actions" style="width:5%;"></th>
												<th _ngcontent-c4="" class="actions" style="width:5%;"></th>
												
											</tr>
										</thead>
										<tbody _ngcontent-c4="" class="no-border-x">
											{% for p in movimientos%} 
													<tr _ngcontent-c4="">
														<td _ngcontent-c4="">{{p.fecha}}</td>
														
														{% if p.tipo == "ingreso" %}
														
														    <td _ngcontent-c4="" class="text-success">ingresaste: ${{p.monto}}</td>
															<td _ngcontent-c4="" class="text-success"> </td>
														{% elif p.tipo == "transferencia" %}
														
														    <td _ngcontent-c4="" class="text-success">transferiste a
														    {{p.cuenta_destino.usuario.username}}: ${{p.monto}}</td>
														    <td _ngcontent-c4="" class="text-success"> </td>
														{% elif p.tipo == "ingreso transferencia"%}
														
														    <td _ngcontent-c4="" class="text-success">recibiste de {{p.cuenta_origen.usuario.username}}: ${{p.monto}} </td>
														    <td _ngcontent-c4="" class="text-success"> </td>
														{% endif %}
														
														
														<td _ngcontent-c4="" class="actions">
															<a href="#" type="button" class="btn btn-danger btn-sm">Detalles</a>
															{% if p.cuenta_destino_id %}
															<!-- Botón para agregar a favoritos -->
															<a href="{% url 'transacciones:agregar_favorito' p.cuenta_destino_id %}" class="btn btn-sm btn-primary">
																Favorito
															</a>
															{% else %}
																<!-- Mostrar algún mensaje si no hay cuenta destino -->
																<span class="text-muted"></span>
															{% endif %}
														</td>
													</tr>
											{% endfor %}

											{% if messages %}
											<div class="container mt-3">
												{% for message in messages %}
												<div class="alert alert-{{ message.tags }}" role="alert">
													{{ message }}
												</div>
												{% endfor %}
											</div>
											{% endif %}		

										</tbody>
									</table>
									
								</div>
							</div>
						</div>
					</div>
				</div>
			


			</div>

        </div>
      </div>
    </div>
  </div>
</main>
			

{% endblock %}

transacciones/templates/listado_motivos.html
						<!-- COMIENZO DEL SECTOR DE TARJETAS DE CANTIDAD-->
{% extends 'base.html' %}

{% block contenido1 %}


{% endblock %}

{% block contenido %}


<main class="container-body">
  <div id="contenido" class="pages-container-fluid pt-2 pb-2 pl-5 pr-5">
    <div class="col-12 col-xl-12 mb-4 align-items-stretch">
      <!-- Mensaje de bienvenida con el nombre del usuario o "invitado" si no está logueado -->
      <h4>Bienvenido,{% if user.is_authenticated %}{{ user.username }}{% else %}invitado{% endif %}!</h4>
      
      <!-- Información de la tarjeta -->
      <div class="card">
        
        <div class="card-body">
         
        	<div id="tabla" class="row">

				<div _ngcontent-c4="" class="col-12 col-xl-12 mb-4 align-items-stretch">
					<div _ngcontent-c4="" class="card h-100 border-0 rounded-0">
						<div _ngcontent-c4="" class="card-title mb-1 p-3 d-flex">
							<h5 class="card-header">LISTADO DE MOTIVOS </h5> <a href="{% url 'transacciones:crear_motivo' %}" type="button" class="btn btn-danger btn-sm">Agregar Nuevo</a>
							<a _ngcontent-c4="" class="btn ml-auto p-0 text-lightning">
								<i _ngcontent-c4="" class="fas fa-ellipsis-h"></i>
							</a>
						</div>
						<div _ngcontent-c4="" class="card-body">
							<div _ngcontent-c4="" class="table-responsive-md">
								<div _ngcontent-c4="" class="table-responsive">
									<table _ngcontent-c4="" class="table ">
										<thead _ngcontent-c4="">
											<tr _ngcontent-c4="">
												
												<th _ngcontent-c4="" style="width:10%;">ID</th>
												<th _ngcontent-c4="" style="width:20%;">NOMBRE</th>
												<th _ngcontent-c4="" class="actions" style="width:5%;"></th>
												<th _ngcontent-c4="" class="actions" style="width:5%;"></th>
												
											</tr>
										</thead>
										<tbody _ngcontent-c4="" class="no-border-x">
											{% for p in motivos%} 
													<tr _ngcontent-c4="">
														<td _ngcontent-c4="">{{p.id}}</td>
														<td _ngcontent-c4="" class="number">{{ p.nombre }}</td>
														<td _ngcontent-c4="" class="actions">
															<a href="{% url 'transacciones:modificar_motivo' p.id %}" type="button" class="btn btn-danger btn-sm">EDITAR</a>
														</td>
														<td _ngcontent-c4="" class="actions">
															<a href="{% url 'transacciones:eliminar_motivo' p.id %}" type="button" class="btn btn-danger btn-sm">ELIMINAR</a>
														</td>
													</tr>
											{% endfor %} 
										</tbody>
									</table>
									
								</div>
							</div>
						</div>
					</div>
				</div>
			


			</div>

        </div>
      </div>
    </div>
  </div>
</main>
			

{% endblock %}

transacciones/templates/monto_tranferencia.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block contenido %}
<main class="container-body">
  <div id="contenido" class="pages-container-fluid pt-4 pb-4 pl-4 pr-4">
    <div class="row">
      <!-- Formulario de transferencia -->
      <div class="col-md-12 mb-4">
        <div class="card border-0 rounded-0">
          <div class="card-title mb-1 p-3">
            <h5>TRANSFERIR DINERO</h5>
          </div>
          <div class="card-body">
            <form method="POST">
              {% csrf_token %}
              <!-- Campo para el usuario (nombre o correo) -->
              <div class="mb-3">
                <label for="usuario" class="form-label">IMPORTE</label>
                <input type="text" class="form-control" id="usuario" name="usuario" placeholder="Ingresa el usuario" required>
                <div id="emailHelp" class="form-text">Ingrese el importe al que desea enviar dinero.</div>
              </div>
              <!-- Botón de continuar -->
              <a class="btn btn-primary" href="{% url 'confirmacion_transferencia' %}"role="button">CONTINUAR</a>
            </form>
          </div>
        </div>
      </div>
    </div>
</main>

<!-- Enlace al JS de Bootstrap (para interacciones, modales, etc.) -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

{% endblock %}

transacciones/templates/saldoinsuficiente.html
{% extends 'base.html' %}
{% block contenido %}
<main class="container-body">
  <div id="contenido" class="pages-container-fluid pt-4 pb-4 pl-4 pr-4">
    <div class="row">
      <div class="col-md-12 mb-4">
        <div class="card border-0 rounded-0 text-center">
          <div class="card-body">
            <h5 class="card-title">Saldo insuficiente</h5>
            <p class="card-text">Intente de nuevo por favor.</p>
            <a href="{% url 'transacciones:realizar_transferencia' %}" class="btn btn-primary">Volver a intentar</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}