FreeTransfer/urls.py
from django.conf import settings
from django.conf.urls.static import static

# FreeTransfer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from . import views
from django.contrib.auth import views as views_django
from django.contrib.auth import authenticate, login as login_django
from django.contrib.auth.views import LoginView
from transacciones.views import MotivoDeleteView,MotivoCreateView,ingresar_dinero,realizar_transferencia

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('login/', views_django.LoginView.as_view(template_name="login.html"), name='login'),
    path('accounts/login/registro/', views.registro, name='registro'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registro/', views.registro, name='registro'),


    # Incluir las rutas de la app transacciones
    path('transacciones/', include('transacciones.urls')),
    path('usuarios/', include('usuarios.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transacciones/urls.py
# movimientos/urls.py
from django.urls import path
from . import views
from transacciones.views import MotivoDeleteView,MotivoCreateView,ingresar_dinero,realizar_transferencia
from usuarios.views import agregar_favorito


app_name = 'transacciones'
urlpatterns = [
    #path('', views.home, name='home'),
    path('ingresar_dinero/', views.ingresar_dinero, name='ingresar_dinero'),
    # transferencia con username como parametro
    path('realizar_transferencia/<str:destinatario_username>/', views.realizar_transferencia, name='realizar_transferencia'),
    path('realizar_transferencia/', views.realizar_transferencia, name='realizar_transferencia'),
    path('confirmacion_transferencia/', views.confirmacion_transferencia, name='confirmacion_transferencia'),
    path('usuarionovalido/', views.realizar_transferencia, name='destinatario_novalido'),
    path('saldoinsuficiente/', views.realizar_transferencia, name='saldoinsuficiente'),
    path('listar_movimientos/', views.listar_movimientos ,name='listar_movimientos'),
    path('listar_motivos/', views.listar_motivos,name='listar_motivos'),
    path('Modificar/<str:pk>', views.ModificarMotivo.as_view(template_name= "modificar_motivo.html"), name='modificar_motivo' ),
    path('eliminar/<int:pk>/',MotivoDeleteView.as_view(), name='eliminar_motivo'),
    path('crear/', MotivoCreateView.as_view(), name='crear_motivo'),
    path('movimientos/favorito/<int:cuenta_destino_id>/', agregar_favorito, name='agregar_favorito'),




    #path('realizar_transferencia/', views.realizar_transferencia, name='realizar_transferencia'),
]

usuarios/urls.py
from django.urls import path

from . import views
from .views import UsuarioDeleteView, EditarPerfilView


app_name = 'usuarios'

urlpatterns = [
    #path('transferencia/', views.transferencia, name='transferencia'),
    path('ingresar_dinero/', views.ingresar_dinero, name='ingresar_dinero'),
    path('ingresar_dinero/confirmacion', views.confirmacion, name='ingresar_dinero'),
    path('realizar_transferencia/', views.realizar_transferencia, name='realizar_transferencia'),
    path('realizar_transferencia/ingresar_monto_transferencia/', views.ingresar_monto_transferencia, name='ingresar_monto_transferencia'),
   	path('realizar_transferencia/ingresar_monto_transferencia/confirmacion', views.confirmacion, name='confirmar_transferencia'),  # Página de confirmación
    path('confirmacion/', views.confirmacion, name='confirmacion'),
    path('tudinero', views.tudinero, name='tudinero'),
    path('tuactividad', views.tuactividad, name='tuactividad'),
    # path('login/', views_django.LoginView.as_view(template_name="login.html"), name='login'),
    path('favoritos/', views.Listar.as_view(), name='favoritos'),
    # eliminar fav
    path('eliminar_favorito/<int:usuario_favorito_id>/', views.eliminar_favorito, name='eliminar_favorito'),
    # detalle vacuna
    path('usuario/<int:pk>/', views.UsuarioPerfil.as_view(), name='perfil'),
    path('perfil/editar/', EditarPerfilView.as_view(), name='editar_perfil'),

    path('eliminar/<int:pk>/',UsuarioDeleteView.as_view(), name='eliminar_usuario'),
    path('listado_usuarios/', views.listar_usuarios,name='listado_usuarios'),
    path('movimiento_por_usuario/<int:pk>/', views.Listar_MovimientosPorUsuario,name='movimiento_por_usuario'),
    path('usuariodenegadp/', views.Listar_MovimientosPorUsuario, name='usuariodenegadp'),

    #path('editar_perfil/<str:pk>', views.EditarPerfil_clase.as_view(template_name= "editarperfil.html"), name='editar_perfil' ),
    # path('editar_perfil/<str:pk>/', views.EditarPerfil_clase.as_view(), name='editar_perfil'),
    path('activar_usuario/<str:pk>/', views.activar_usuario.as_view(), name='activar_usuario'),
    

]





 

usuarios/forms.py
# forms.py
from django import forms
from .models import Transferencia
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario
from django import forms
from django.core.exceptions import ValidationError


class TransferenciaForm(forms.ModelForm):
    class Meta:
        model = Transferencia
        fields = ['usuario_destino', 'monto', 'motivo']
        widgets = {
            'usuario_destino': forms.Select(attrs={'class': 'form-control'}),
            'monto': forms.NumberInput(attrs={'class': 'form-control'}),
            'motivo': forms.Textarea(attrs={'class': 'form-control'}),
        }


from django import forms

class IngresoDineroForm(forms.Form):
    importe = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
        label='Importe a ingresar',
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Ingresa el importe'})
    )



class FormUser(UserCreationForm):
    
    username = forms.CharField(label="Nombre de usuario", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese un nombre de usuario'}))
    class Meta:
        model = Usuario
        fields = ["username", "first_name", "last_name", "email", "dni"]
    
    def __init__(self, *args, **kwargs):
        super(FormUser, self).__init__(*args, **kwargs)

        add_class_form_control = ["first_name", "username", "last_name", "email", "dni", "password1", "password2"]
        
        for attr_field in add_class_form_control:
            self.fields[attr_field].widget.attrs["class"] = "form-control"
    
    # creamos una nueva validación la cual se incorpora a los ya activos en el form
    def clean_dni(self):
        dni = self.cleaned_data["dni"]
        if not ( 7 <= len(str(dni)) <= 8 ):
            raise ValidationError("Dni debe contener entre 7 y 8 caracteres")
        return dni


class EditarPerfilForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['first_name', 'last_name', 'email', 'avatar']  # Solo los campos que deseas permitir editar
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo'}),
            'avatar': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }
        
        
class EditarPerfil(forms.ModelForm):

    class Meta:
        model = Usuario
        fields = ['username','email','dni','avatar','is_active']



class ActivarUsuario(forms.ModelForm):

    class Meta:
        model = Usuario
        fields = ['username','is_active']



class EditarPerfil(forms.ModelForm):

    class Meta:
        model = Usuario
        fields = ['username','email','dni','avatar','is_active']

usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Usuario, Transferencia, MotivoTransferencia
from django.contrib.auth.forms import UserCreationForm
from usuarios.models import Usuario
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy
from django.views.generic import TemplateView, UpdateView, DetailView
from django import forms
from django.contrib import messages
from django.contrib.auth import authenticate, login as login_django
from .models import UsuarioFavorito, Usuario, Transferencia, MotivoTransferencia
from .forms import FormUser, ActivarUsuario
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView
from .forms import EditarPerfilForm, EditarPerfil

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm










def register(request):
    if request.method == 'POST':
        form = FormUser(request.POST, request.FILES)
        if form.is_valid():
            # Obtén los datos del formulario
            password = form.cleaned_data['password1']
            user = form.save(commit=False)  # No guarda el usuario todavía

            # Encripta la contraseña
            user.set_password(password)  # Este método encripta la contraseña
            user.save()  # Guarda el usuario

            return redirect('login')  # Redirige a la página de login
    else:
        form = FormUser()

    return render(request, 'registro.html', {'form': form})


#@user_passes_test(is_staff)
def Listar_MovimientosPorUsuario(request, pk):
    # Verificar si el usuario no es staff
    if not request.user.is_staff:
        messages.error(request, "No tienes permisos para acceder a esta página.")
        return render(request, 'usuarios/denegado.html')
    # Obtener el usuario directamente por el pk (ID del usuario)
    usuario = Usuario.objects.get(pk=pk)
    
    # Obtener la cuenta del usuario
    cuenta = Cuenta.objects.get(usuario=usuario)
    
    # Obtener los movimientos de la cuenta
    movimientos = Movimiento.objects.filter(cuenta_origen=cuenta) | Movimiento.objects.filter(cuenta_destino=cuenta)
    
    # Pasar los movimientos a la plantilla
    context = {
        'usuario': usuario,
        'movimientos': movimientos
    }
    
    return render(request, 'usuarios/movimientos_por_usuario.html', context)



def iniciar_sesion(request):
    se_autentico = False
    salio_mal = False
    mensaje_error = ""
    username = ""

    if request.method == "POST":
        username = request.POST.get("username", default=None)
        password = request.POST.get("password", default=None)
        usuario = authenticate(request, username=username, password=password)

        se_autentico = True

        if usuario:
            salio_mal = False
            login_django(request, usuario)
            
    return render(request, 'login.html', {})



def tudinero(request):
    # Obtener el importe de la sesión, si está disponible
    importe = request.session.get('importe', 0)
    return render(request, 'tu_dinero.html', {'importe': importe})

def tuactividad(request):
    
    return render(request, 'tu_actividad.html')


def ingresar_dinero(request):
        
    return render(request, 'ingresar_dinero.html')


def realizar_transferencia(request):
    
    return render(request, 'transferencia.html')

def ingresar_monto_transferencia(request):
        
    return render(request, 'monto_tranferencia.html')


def confirmacion(request):
    # Tu lógica para manejar la transferencia
    return render(request, 'confirmacion.html')


class UsuarioDeleteView(DeleteView):
    model = Usuario
    template_name = 'usuarios/confirmacion_eliminar_usuario.html'
    success_url = reverse_lazy('usuarios:listado_usuarios')  # Redirige tras eliminar

def listar_usuarios(request):
    if not request.user.is_staff:
        messages.error(request, "No tienes permisos para acceder a esta página.")
        return render(request, 'usuarios/denegado.html')
    context={}
    todos=Usuario.objects.all() #MotivoTransferencia.objects.all()
    context['usuarios']=todos
    return render(request,'usuarios/listado_usuarios.html', context)
    if not request.user.is_staff:
        messages.error(request, "No tienes permisos para acceder a esta página.")
        return render(request, 'usuarios/denegado.html')
    

# @login_required
class Listar(TemplateView):
    template_name = 'usuarios/favoritos.html'
    # model = UsuarioFavorito
    context_object_name = "usuario"
    # paginate_by = 5
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        # Obtener el usuario actual basado en el pk de la URL
        # usuario_origen_id = self.kwargs.get('pk')
        # usuario = get_object_or_404(Usuario, id=usuario_origen_id)
        usuario = self.request.user
        # Filtrar favoritos para este usuario
        ctx['favoritos'] = UsuarioFavorito.objects.filter(usuario_origen=usuario)
        ctx["titulo"] = "LISTA DE FAVORITOS"
        return ctx
    
    
class UsuarioPerfil(DetailView):
    model = Usuario
    template_name = 'usuarios/perfil.html'
    context_object_name = 'usuario'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['usuario'] = Usuario.objects.filter(id=self.object.id)
        return context
    
    
class EditarPerfilView(LoginRequiredMixin, UpdateView):
    model = Usuario
    form_class = EditarPerfilForm
    template_name = 'usuarios/editar_perfil.html'
    def get_success_url(self):
        # Redirige al perfil del usuario logueado
        return reverse_lazy('usuarios:perfil', kwargs={'pk': self.request.user.pk})
    def get_object(self, queryset=None):
        print("Usuario que edita:", self.request.user)  # Depuración
        # Retorna el usuario logueado para que edite su propio perfil
        return self.request.user
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print("Formulario generado:", context.get("form"))
        return context
    

class EditarPerfil_clase(UpdateView):
    model = Usuario
    form_class = EditarPerfil
    template_name = 'usuarios/editarperfil.html'

    def get_success_url(self):
        # Verificar si el usuario es parte del personal (is_staff)
        if self.request.user.is_staff:
            return reverse_lazy('usuarios:listado_usuarios')  # Redirigir a listado de usuarios si es staff
        else:
            return reverse_lazy('home')  # Redirigir al home si no es staff

    def form_valid(self, form):
        perfil = form.save(commit=False)
        
        perfil.save()
        return redirect(self.get_success_url())  # Usar el método get_success_url para redirigir


class activar_usuario(UpdateView):
    model = Usuario
    form_class = ActivarUsuario
    template_name = 'usuarios/activar_usuario.html'
    success_url = reverse_lazy('usuarios:listado_usuarios')

    # Redirigir al home si no es staff

    def form_valid(self, form):
        perfil = form.save(commit=False)
        perfil.save()
        return redirect(self.get_success_url())  # Usar el método get_success_url para redirigir



from transacciones.models import Cuenta  # Modelo donde resides las cuentas

@login_required
def agregar_favorito(request, cuenta_destino_id):
    # Obtener la cuenta destino
    cuenta_destino = get_object_or_404(Cuenta, id=cuenta_destino_id)

    # Obtener el usuario asociado a la cuenta destino
    usuario_destino = cuenta_destino.usuario

    # Validar que el usuario destino no sea el usuario logueado
    if usuario_destino == request.user:
        messages.error(request, "No puedes agregarte a ti mismo como favorito.")
        return redirect(request.META.get('HTTP_REFERER', '/'))  # Cambia esta URL según tu ruta de movimientos

    # Validar que no se haya agregado previamente como favorito
    favorito_existente = UsuarioFavorito.objects.filter(
        usuario_origen=request.user,
        usuario_favorito=usuario_destino
    ).exists()

    if favorito_existente:
        messages.info(request, "El usuario ya está en tu lista de favoritos.")
    else:
        # Crear el nuevo favorito
        UsuarioFavorito.objects.create(
            usuario_origen=request.user,
            usuario_favorito=usuario_destino
        )
        messages.success(request, "Usuario agregado a tus favoritos con éxito.")

    return redirect(request.META.get('HTTP_REFERER', '/'))  # Cambia esta URL según la lista de movimientos



@login_required
def eliminar_favorito(request, usuario_favorito_id):
    # Obtener el favorito a eliminar
    favorito = get_object_or_404(UsuarioFavorito, usuario_favorito_id=usuario_favorito_id, usuario_origen=request.user)

    # Eliminar el usuario favorito
    favorito.delete()

    messages.success(request, "El usuario ha sido eliminado de tu lista de favoritos.")
    
    # Redirigir de vuelta a la lista de favoritos
    return redirect('usuarios:favoritos')  # Asegúrate de que esta URL sea correcta

usuarios/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    

    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" />
     <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>
    <!--<link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.css" rel="stylesheet"/>
    -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css">
    <link rel="stylesheet" href='{% static "index.css" %}'>
    <link rel="stylesheet" type="text/css" href='{% static "style.css" %}'>

  <title>FreeTransfer</title>

 
</head>


<body class='body-collapsed'>
<!----------------------------------------------menu lateral------------------------------------------------------------------------------------------
--->
  
  <div id="sidemenu" class="menu-collapsed">
    
    
    <div id="header">
    
      <div class="sidebar-brand">
        <a id="title" href="#"> FreeTransfer</a>
        <div id="menu--btn" class="">
          <i class="fas fa-bars"></i>
        </div>
      </div>
      
    </div>

    
   

    <div id="profile">
      <div id="photo">
        <img 
        src="{% if user.avatar %}{{ user.avatar.url }}{% else %}{% static 'user_default.png' %}{% endif %}" 
        class="rounded-circle img-fluid" 
        style="width: 80px; height: 80px; object-fit: cover;" 
        alt="User Image">
      </div>
      <div id=name><span>{{user.first_name}}</span></div>
      
    </div>
    
    <script>
      // Selecciona los elementos necesarios
      const sidemenu = document.getElementById('sidemenu');
      const userImage = document.getElementById('user-image');
    
      // Función para ajustar el tamaño de la imagen
      function adjustImageSize() {
        if (sidemenu.classList.contains('menu-collapsed')) {
          userImage.style.width = '30px';
          userImage.style.height = '30px';
        } else {
          userImage.style.width = '80px';
          userImage.style.height = '80px';
        }
      }
    
      // Llama a la función al cargar la página
      adjustImageSize();
    
      // Configura un MutationObserver para detectar cambios en las clases
      const observer = new MutationObserver(() => {
        adjustImageSize(); // Llama a la función cuando cambie la clase
      });
    
      // Observa cambios en los atributos del sidemenu
      observer.observe(sidemenu, { attributes: true, attributeFilter: ['class'] });
    </script>


    
    <div id="menu-items">

       <div class="item">
        <a href="{% url 'home' %}">
          <div class="icon">
            <img src="{% static 'iconos/hogar.png' %}"></div>
          <div class="title"><span>Home</span></div>
        </a>
        </div>
 
      <div class="item">
        <a href="#">
          <div class="icon">
                 <img src="{% static 'iconos/billete.png' %}"></div>
                <div class="title"><span>Tu dinero</span></div>
                
            </a>
      </div>

      <div class="item">
        <a href="{% url 'transacciones:listar_movimientos' %}">
          <div class="icon">
            <img src="{% static 'iconos/anadir.png' %}"></div>
          <div class="title"><span>Tu actividad</span></div>
        </a>
      </div>
     
      <div class="item">
       <a href="{% url 'transacciones:realizar_transferencia' %}">
          <div class="icon"><img src="{% static 'iconos/lista.png' %}"></div>
          <div class="title"><span>Transferir</span></div>
        </a>
      </div>

      {% if user.is_staff == True%}
        <div class="item">
         <a href="{% url 'transacciones:listar_motivos' %}">
            <div class="icon"><img src="{% static 'iconos/lista.png' %}"></div>
            <div class="title"><span>Listar Motivos</span></div>
          </a>
        </div>
        <div class="item">
         <a href="{% url 'usuarios:listado_usuarios' %}">
            <div class="icon"><img src="{% static 'iconos/lista.png' %}"></div>
            <div class="title"><span>Listar Usuarios</span></div>
          </a>
        </div>
        {% endif %}
      <div class="item">
        <a href="#">
          <div class="icon">
            <img src="{% static 'iconos/identificacion.png' %}"></div>
          <div class="title"><span>Cerrar Sesion</span></div>
        </a>
      </div>
      
         
    </div>
  </div>
<!--  aca termine el menu lateral ----------------------------------------------------------------------->

<!-- header de la pagina principal ---------------------------------------------------------------------->
  
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">FreeTransfer</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'usuarios:favoritos'%}">Favoritos</a>
      </li>
      <li class="nav-item">
        <a href="#">
      </li>
      <li class="nav-item">
        <a href="#">
      </li>
      <li class="nav-item">
       <a href="#">
      </li>
     
    </ul>
      <div class="nav-item dropdown pr-2 pl-5">
        <a class="dropdown-toggle text-light " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{user.first_name}}
        </a>
        <div class="dropdown-menu bg-dark text-light" aria-labelledby="navbarDropdown">
          <img 
            src="{% if user.avatar %}{{ user.avatar.url }}{% else %}{% static 'user_default.png' %}{% endif %}" 
            class="rounded-circle img-fluid ml-4" 
            style="width: 80px; height: 80px; object-fit: cover;" 
            alt="User Image">

          <a class="dropdown-item text-light " href="{% url 'usuarios:perfil' user.id %}">VER PERFIL</a>
          <a class="dropdown-item text-light" href="#">CAMBIAR CONTRASEÑA</a>
          <div class="dropdown-divider text-light "></div>

           <form method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <input type="hidden" name="next" value="{% url 'login' %}">
              <button class="btn-primary ml-4 rounded" type="submit">Cerrar sesión</button>
          </form>

        </div>
      </div>
  </div>
</nav>









  
  {% block contenido %}
        
  {% endblock %}











<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


  <script>
    const btn = document.querySelector('#menu--btn');
    const menu = document.querySelector('#sidemenu');
    btn.addEventListener('click', e => {
      menu.classList.toggle("menu-expanded");
      menu.classList.toggle("menu-collapsed");

      document.querySelector('body').classList.toggle('body-expanded');
    });
  </script>
</body>
</html>

usuarios/templates/login.html
{% load static %}
{% load crispy_forms_tags %}

{% block contenido %}

<section id="loguin" class="login">
	<div class="container-lg">
      <div id="tabla" class="row">

        <div class="col-sm-12 col-xl-12 mb-12 align-items-stretch">
          
        	<div class="form-row justify-content-center">
          <div class="card h-100 border-0 rounded-0">
            <div class="card-title d-flex">

            </div>
            <div class="card-body">
              
			<div class="form-group border rounded">
				<div class="col-lg-4 mx-auto">
					<img src="{% static 'images/user.svg' %}" width="50" height="50" alt="">
				</div>
				<h2 class="text-center my-3">Ingresar</h2>
				{{ form.errors }}
				<form method="POST">{% csrf_token %}
					<div class="col-12">
						{{ form.username|as_crispy_field }}
					</div>
					<div class="col-12 form-group">
						{{ form.password|as_crispy_field }}
					</div>
					<p>Si no tenés una cuenta <a class="text-dark" href="{% url 'usuarios:registrar' %}">Registrate</a></p>
					<p>¿olvidaste la contraseña? <a class="text-dark" href="#">Recuperala aquí</a></p>
					<div class="col-xl-8 ml-5 mr-5 pl-5 pr-5 ">
						
						<button type="submit" class="btn btn-dark" value="Ingresar" name="">Ingresar</button>
					</div>
				

				</form>
			</div>
		</div>
            </div>
          </div>
        </div>
      






		
	</div>
</section>
{% endblock %}