FreeTransfer/urls.py
from django.conf import settings
from django.conf.urls.static import static

# FreeTransfer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from . import views
from django.contrib.auth import views as views_django
from django.contrib.auth import authenticate, login as login_django
from django.contrib.auth.views import LoginView
from transacciones.views import MotivoDeleteView,MotivoCreateView,ingresar_dinero,realizar_transferencia

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('login/', views_django.LoginView.as_view(template_name="login.html"), name='login'),
    path('accounts/login/registro/', views.registro, name='registro'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registro/', views.registro, name='registro'),


    # Incluir las rutas de la app transacciones
    path('transacciones/', include('transacciones.urls')),
    path('usuarios/', include('usuarios.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transacciones/urls.py
# movimientos/urls.py
from django.urls import path
from . import views
from transacciones.views import MotivoDeleteView,MotivoCreateView,ingresar_dinero,realizar_transferencia
from usuarios.views import agregar_favorito


app_name = 'transacciones'
urlpatterns = [
    #path('', views.home, name='home'),
    path('ingresar_dinero/', views.ingresar_dinero, name='ingresar_dinero'),
    # transferencia con username como parametro
    path('realizar_transferencia/<str:destinatario_username>/', views.realizar_transferencia, name='realizar_transferencia'),
    path('realizar_transferencia/', views.realizar_transferencia, name='realizar_transferencia'),
    path('confirmacion_transferencia/', views.confirmacion_transferencia, name='confirmacion_transferencia'),
    path('usuarionovalido/', views.realizar_transferencia, name='destinatario_novalido'),
    path('saldoinsuficiente/', views.realizar_transferencia, name='saldoinsuficiente'),
    path('listar_movimientos/', views.listar_movimientos ,name='listar_movimientos'),
    path('listar_motivos/', views.listar_motivos,name='listar_motivos'),
    path('Modificar/<str:pk>', views.ModificarMotivo.as_view(template_name= "modificar_motivo.html"), name='modificar_motivo' ),
    path('eliminar/<int:pk>/',MotivoDeleteView.as_view(), name='eliminar_motivo'),
    path('crear/', MotivoCreateView.as_view(), name='crear_motivo'),
    path('movimientos/favorito/<int:cuenta_destino_id>/', agregar_favorito, name='agregar_favorito'),




    #path('realizar_transferencia/', views.realizar_transferencia, name='realizar_transferencia'),
]

usuarios/urls.py
from django.urls import path

from . import views
from .views import UsuarioDeleteView, EditarPerfilView


app_name = 'usuarios'

urlpatterns = [
    #path('transferencia/', views.transferencia, name='transferencia'),
    path('ingresar_dinero/', views.ingresar_dinero, name='ingresar_dinero'),
    path('ingresar_dinero/confirmacion', views.confirmacion, name='ingresar_dinero'),
    path('realizar_transferencia/', views.realizar_transferencia, name='realizar_transferencia'),
    path('realizar_transferencia/ingresar_monto_transferencia/', views.ingresar_monto_transferencia, name='ingresar_monto_transferencia'),
   	path('realizar_transferencia/ingresar_monto_transferencia/confirmacion', views.confirmacion, name='confirmar_transferencia'),  # Página de confirmación
    path('confirmacion/', views.confirmacion, name='confirmacion'),
    path('tudinero', views.tudinero, name='tudinero'),
    path('tuactividad', views.tuactividad, name='tuactividad'),
    # path('login/', views_django.LoginView.as_view(template_name="login.html"), name='login'),
    path('favoritos/', views.Listar.as_view(), name='favoritos'),
    # eliminar fav
    path('eliminar_favorito/<int:usuario_favorito_id>/', views.eliminar_favorito, name='eliminar_favorito'),
    # detalle vacuna
    path('usuario/<int:pk>/', views.UsuarioPerfil.as_view(), name='perfil'),
    path('perfil/editar/', EditarPerfilView.as_view(), name='editar_perfil'),

    path('eliminar/<int:pk>/',UsuarioDeleteView.as_view(), name='eliminar_usuario'),
    path('listado_usuarios/', views.listar_usuarios,name='listado_usuarios'),
    path('movimiento_por_usuario/<int:pk>/', views.Listar_MovimientosPorUsuario,name='movimiento_por_usuario'),
    path('usuariodenegadp/', views.Listar_MovimientosPorUsuario, name='usuariodenegadp'),

    #path('editar_perfil/<str:pk>', views.EditarPerfil_clase.as_view(template_name= "editarperfil.html"), name='editar_perfil' ),
    # path('editar_perfil/<str:pk>/', views.EditarPerfil_clase.as_view(), name='editar_perfil'),
    path('activar_usuario/<str:pk>/', views.activar_usuario.as_view(), name='activar_usuario'),
    

]





 

usuarios/forms.py
# forms.py
from django import forms
from .models import Transferencia
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario
from django import forms
from django.core.exceptions import ValidationError


class TransferenciaForm(forms.ModelForm):
    class Meta:
        model = Transferencia
        fields = ['usuario_destino', 'monto', 'motivo']
        widgets = {
            'usuario_destino': forms.Select(attrs={'class': 'form-control'}),
            'monto': forms.NumberInput(attrs={'class': 'form-control'}),
            'motivo': forms.Textarea(attrs={'class': 'form-control'}),
        }


from django import forms

class IngresoDineroForm(forms.Form):
    importe = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
        label='Importe a ingresar',
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Ingresa el importe'})
    )



class FormUser(UserCreationForm):
    
    username = forms.CharField(label="Nombre de usuario", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese un nombre de usuario'}))
    class Meta:
        model = Usuario
        fields = ["username", "first_name", "last_name", "email", "dni"]
    
    def __init__(self, *args, **kwargs):
        super(FormUser, self).__init__(*args, **kwargs)

        add_class_form_control = ["first_name", "username", "last_name", "email", "dni", "password1", "password2"]
        
        for attr_field in add_class_form_control:
            self.fields[attr_field].widget.attrs["class"] = "form-control"
    
    # creamos una nueva validación la cual se incorpora a los ya activos en el form
    def clean_dni(self):
        dni = self.cleaned_data["dni"]
        if not ( 7 <= len(str(dni)) <= 8 ):
            raise ValidationError("Dni debe contener entre 7 y 8 caracteres")
        return dni


class EditarPerfilForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['first_name', 'last_name', 'email', 'avatar']  # Solo los campos que deseas permitir editar
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo'}),
            'avatar': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }
        
        
class EditarPerfil(forms.ModelForm):

    class Meta:
        model = Usuario
        fields = ['username','email','dni','avatar','is_active']



class ActivarUsuario(forms.ModelForm):

    class Meta:
        model = Usuario
        fields = ['username','is_active']



class EditarPerfil(forms.ModelForm):

    class Meta:
        model = Usuario
        fields = ['username','email','dni','avatar','is_active']

usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Usuario, Transferencia, MotivoTransferencia
from django.contrib.auth.forms import UserCreationForm
from usuarios.models import Usuario
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy
from django.views.generic import TemplateView, UpdateView, DetailView
from django import forms
from django.contrib import messages
from django.contrib.auth import authenticate, login as login_django
from .models import UsuarioFavorito, Usuario, Transferencia, MotivoTransferencia
from .forms import FormUser, ActivarUsuario
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView
from .forms import EditarPerfilForm, EditarPerfil

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm










def register(request):
    if request.method == 'POST':
        form = FormUser(request.POST, request.FILES)
        if form.is_valid():
            # Obtén los datos del formulario
            password = form.cleaned_data['password1']
            user = form.save(commit=False)  # No guarda el usuario todavía

            # Encripta la contraseña
            user.set_password(password)  # Este método encripta la contraseña
            user.save()  # Guarda el usuario

            return redirect('login')  # Redirige a la página de login
    else:
        form = FormUser()

    return render(request, 'registro.html', {'form': form})


#@user_passes_test(is_staff)
def Listar_MovimientosPorUsuario(request, pk):
    # Verificar si el usuario no es staff
    if not request.user.is_staff:
        messages.error(request, "No tienes permisos para acceder a esta página.")
        return render(request, 'usuarios/denegado.html')
    # Obtener el usuario directamente por el pk (ID del usuario)
    usuario = Usuario.objects.get(pk=pk)
    
    # Obtener la cuenta del usuario
    cuenta = Cuenta.objects.get(usuario=usuario)
    
    # Obtener los movimientos de la cuenta
    movimientos = Movimiento.objects.filter(cuenta_origen=cuenta) | Movimiento.objects.filter(cuenta_destino=cuenta)
    
    # Pasar los movimientos a la plantilla
    context = {
        'usuario': usuario,
        'movimientos': movimientos
    }
    
    return render(request, 'usuarios/movimientos_por_usuario.html', context)



def iniciar_sesion(request):
    se_autentico = False
    salio_mal = False
    mensaje_error = ""
    username = ""

    if request.method == "POST":
        username = request.POST.get("username", default=None)
        password = request.POST.get("password", default=None)
        usuario = authenticate(request, username=username, password=password)

        se_autentico = True

        if usuario:
            salio_mal = False
            login_django(request, usuario)
            
    return render(request, 'login.html', {})



def tudinero(request):
    # Obtener el importe de la sesión, si está disponible
    importe = request.session.get('importe', 0)
    return render(request, 'tu_dinero.html', {'importe': importe})

def tuactividad(request):
    
    return render(request, 'tu_actividad.html')


def ingresar_dinero(request):
        
    return render(request, 'ingresar_dinero.html')


def realizar_transferencia(request):
    
    return render(request, 'transferencia.html')

def ingresar_monto_transferencia(request):
        
    return render(request, 'monto_tranferencia.html')


def confirmacion(request):
    # Tu lógica para manejar la transferencia
    return render(request, 'confirmacion.html')


class UsuarioDeleteView(DeleteView):
    model = Usuario
    template_name = 'usuarios/confirmacion_eliminar_usuario.html'
    success_url = reverse_lazy('usuarios:listado_usuarios')  # Redirige tras eliminar

def listar_usuarios(request):
    if not request.user.is_staff:
        messages.error(request, "No tienes permisos para acceder a esta página.")
        return render(request, 'usuarios/denegado.html')
    context={}
    todos=Usuario.objects.all() #MotivoTransferencia.objects.all()
    context['usuarios']=todos
    return render(request,'usuarios/listado_usuarios.html', context)
    if not request.user.is_staff:
        messages.error(request, "No tienes permisos para acceder a esta página.")
        return render(request, 'usuarios/denegado.html')
    

# @login_required
class Listar(TemplateView):
    template_name = 'usuarios/favoritos.html'
    # model = UsuarioFavorito
    context_object_name = "usuario"
    # paginate_by = 5
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        # Obtener el usuario actual basado en el pk de la URL
        # usuario_origen_id = self.kwargs.get('pk')
        # usuario = get_object_or_404(Usuario, id=usuario_origen_id)
        usuario = self.request.user
        # Filtrar favoritos para este usuario
        ctx['favoritos'] = UsuarioFavorito.objects.filter(usuario_origen=usuario)
        ctx["titulo"] = "LISTA DE FAVORITOS"
        return ctx
    
    
class UsuarioPerfil(DetailView):
    model = Usuario
    template_name = 'usuarios/perfil.html'
    context_object_name = 'usuario'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['usuario'] = Usuario.objects.filter(id=self.object.id)
        return context
    
    
class EditarPerfilView(LoginRequiredMixin, UpdateView):
    model = Usuario
    form_class = EditarPerfilForm
    template_name = 'usuarios/editar_perfil.html'
    def get_success_url(self):
        # Redirige al perfil del usuario logueado
        return reverse_lazy('usuarios:perfil', kwargs={'pk': self.request.user.pk})
    def get_object(self, queryset=None):
        print("Usuario que edita:", self.request.user)  # Depuración
        # Retorna el usuario logueado para que edite su propio perfil
        return self.request.user
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print("Formulario generado:", context.get("form"))
        return context
    

class EditarPerfil_clase(UpdateView):
    model = Usuario
    form_class = EditarPerfil
    template_name = 'usuarios/editarperfil.html'

    def get_success_url(self):
        # Verificar si el usuario es parte del personal (is_staff)
        if self.request.user.is_staff:
            return reverse_lazy('usuarios:listado_usuarios')  # Redirigir a listado de usuarios si es staff
        else:
            return reverse_lazy('home')  # Redirigir al home si no es staff

    def form_valid(self, form):
        perfil = form.save(commit=False)
        
        perfil.save()
        return redirect(self.get_success_url())  # Usar el método get_success_url para redirigir


class activar_usuario(UpdateView):
    model = Usuario
    form_class = ActivarUsuario
    template_name = 'usuarios/activar_usuario.html'
    success_url = reverse_lazy('usuarios:listado_usuarios')

    # Redirigir al home si no es staff

    def form_valid(self, form):
        perfil = form.save(commit=False)
        perfil.save()
        return redirect(self.get_success_url())  # Usar el método get_success_url para redirigir



from transacciones.models import Cuenta  # Modelo donde resides las cuentas

@login_required
def agregar_favorito(request, cuenta_destino_id):
    # Obtener la cuenta destino
    cuenta_destino = get_object_or_404(Cuenta, id=cuenta_destino_id)

    # Obtener el usuario asociado a la cuenta destino
    usuario_destino = cuenta_destino.usuario

    # Validar que el usuario destino no sea el usuario logueado
    if usuario_destino == request.user:
        messages.error(request, "No puedes agregarte a ti mismo como favorito.")
        return redirect(request.META.get('HTTP_REFERER', '/'))  # Cambia esta URL según tu ruta de movimientos

    # Validar que no se haya agregado previamente como favorito
    favorito_existente = UsuarioFavorito.objects.filter(
        usuario_origen=request.user,
        usuario_favorito=usuario_destino
    ).exists()

    if favorito_existente:
        messages.info(request, "El usuario ya está en tu lista de favoritos.")
    else:
        # Crear el nuevo favorito
        UsuarioFavorito.objects.create(
            usuario_origen=request.user,
            usuario_favorito=usuario_destino
        )
        messages.success(request, "Usuario agregado a tus favoritos con éxito.")

    return redirect(request.META.get('HTTP_REFERER', '/'))  # Cambia esta URL según la lista de movimientos



@login_required
def eliminar_favorito(request, usuario_favorito_id):
    # Obtener el favorito a eliminar
    favorito = get_object_or_404(UsuarioFavorito, usuario_favorito_id=usuario_favorito_id, usuario_origen=request.user)

    # Eliminar el usuario favorito
    favorito.delete()

    messages.success(request, "El usuario ha sido eliminado de tu lista de favoritos.")
    
    # Redirigir de vuelta a la lista de favoritos
    return redirect('usuarios:favoritos')  # Asegúrate de que esta URL sea correcta

usuarios/templates/usuarios/activar_usuario.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block contenido1 %}
<p>Tickets</p>

{% endblock %}


{% block contenido %}
            <!-- COMIENZO DEL SECTOR DE TARJETAS DE CANTIDAD-->

            
           


<main class="container-body">
  <div id="contenido" class="pages-container-fluid pt-4 pb-4 pl-4 pr-4">
    <div>
      <h4>vista administrador: Activar Usuario</h4>
      <div id="tarjetas" class="row">
        

      </div>


            <!-- COMIENZO DEL SECTOR DE TABLA DE TICKETS  -->


<div id="contenido"  class="pages-container-fluid pt-2 pb-2 pl-5 pr-5">

  <div class="col-12 col-xl-12 mb-4 align-items-stretch">

    <div class="card h-100 border-0 rounded">

      <div id="tabla" class="row">

        <div _ngcontent-c4="" class="col-sm-12 col-xl-8 mb-4 align-items-stretch">
          
      
      <div _ngcontent-c4="" class="col-sm-12 col-xl-4 mb-4 align-items-stretch">
          
            <div _ngcontent-c4="" class="card-title mb-1 p-3 d-flex">
              <h4>Activar Usuario:</h4>
              <a _ngcontent-c4="" class="btn ml-auto p-0 text-lightning">
                <i _ngcontent-c4="" class="fas fa-ellipsis-h"></i>
              </a>
            </div>
            <div _ngcontent-c4="" class="card-body">
                <div>
                      
                    {{form.errors}}
                    <form method="POST">{% csrf_token %}
                 
                      <div class="col-lg-12 col-sm-12 mr-auto my-3">
                          {{form.username|as_crispy_field}}
                      </div>
                      <div class="col-lg-12 col-sm-12 mr-auto my-3">
                          {{form.is_active|as_crispy_field}}
                      </div>
                      
            
                      <input class="align-center" type="submit" value="Guardar">
                    </form> 
                </div>



            </div>
        
        

     
      </div>
    </div>
    </div>
    </div>
    </div>

  </div>
  

</main>
 

{% endblock %}

usuarios/templates/usuarios/favoritos.html
{% extends 'base.html' %}
{% load static %}


{% block contenido %}
  <!-- COMIENZO DEL SECTOR DE TABLA DE FAVORITOS  -->

  {% if messages %}
  <div class="alert alert-success" role="alert">
      {% for message in messages %}
          <p>{{ message }}</p>
      {% endfor %}
  </div>
  {% endif %}

  <div id="contenido"  class="pages-container-fluid pt-2 pb-2 pl-5 pr-5">

    <div class="col-12 col-xl-12 mb-4 align-items-stretch">
        <div class="card h-100 border-0 rounded">
            <div class="card-title mb-1">                                 
            
                <div class="table-responsive-md">
                    <div _ngcontent-c4="" class="table-responsive">
                      <table class="table">
                        <thead>
                            <tr>
                                <th style="width:5%;">NOMBRE</th>
                                <th style="width:16%;">APELLIDO</th>
                                <th class="actions" style="width:3%;">Transferir</th>
                                <th class="actions" style="width:3%;">Eliminar</th>
  
                            </tr>
                        </thead>
                        <tbody class="no-border-x">
                            {% if favoritos %}
                                {% for fav in favoritos %}
                                <tr>
                                    <td>{% if fav.usuario_favorito.first_name %}{{ fav.usuario_favorito.first_name|capfirst }}{% else %}USERNAME: {{ fav.usuario_favorito.username }} {% endif %}</td>
                                    <td>{{ fav.usuario_favorito.last_name|capfirst }}</td>
                                    <td class="actions">
                                        <a href="{% url 'transacciones:realizar_transferencia' fav.usuario_favorito.username %}" class="btn btn-primary btn-sm">
                                          <span class="icon-checkmark"></span></a>
                                    </td>
                                    <td class="actions">
                                        <a href="{% url 'usuarios:eliminar_favorito' fav.usuario_favorito.id %}" class="btn btn-danger btn-sm" onclick="return confirm('¿Estás seguro de que deseas eliminar este usuario de tu lista de favoritos?');"><span class="icon-cross"></span></a>
                                    </td>
                                </tr>
                                {% endfor %}
                            {% else %}
                            <tr>
                                <!-- Espaciamos el mensaje para que abarque las columnas -->
                                <td colspan="5" class="text-center text-muted" style="font-size: 1.5rem; font-weight: bold;">No posee usuarios favoritos</td>
                            </tr>
                            {% endif %}
                        </tbody>
                    </table>
                    
                        
                    </div>
                </div>
                <div  class="card-footer">
                  <div  class="legend d-flex justify-content-center"></div>
                </div>
            </div>
        </div>
    </div>
  </div>
{% endblock %}

  

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


  <script>
    const btn = document.querySelector('#menu--btn');
    const menu = document.querySelector('#sidemenu');
    btn.addEventListener('click', e => {
      menu.classList.toggle("menu-expanded");
      menu.classList.toggle("menu-collapsed");

      document.querySelector('body').classList.toggle('body-expanded');
    });
  </script>
</body>
</html>

usuarios/templates/usuarios/home.html
{% extends 'base.html' %}

{% block contenido1 %}
<p>Tickets</p>

{% endblock %}


{% block contenido %}
                        <!-- COMIENZO DEL SECTOR DE TARJETAS DE CANTIDAD-->


<main class="container-body">
  <div id="contenido" class="pages-container-fluid pt-2 pb-2 pl-5 pr-5">
    <div class="col-12 col-xl-12 mb-4 align-items-stretch">
      <h4>Bienvenido, {% if user.is_authenticated %}{{ user.first_name }}{% else %}Invitado{% endif %}!</h4>
      <div class="card">
        <h5 class="card-header">Dinero disponible</h5>
        <div class="card-body">
          <h5 class="card-title">{% if monto > 0 %}$ {{ monto }}{% else %}No posee fondos{% endif %}</h5>
          <a class="btn btn-primary" href="{% url 'transacciones:ingresar_dinero' %}" role="button">Ingresar Dinero</a>
          <a class="btn btn-primary" href="{% url 'transacciones:realizar_transferencia' %}">Transferir Dinero</a>
        </div>
      </div>
    </div>
  </div>
</main>





                        <!-- COMIENZO DEL SECTOR DE TABLA DE TICKETS  -->




{% endblock %}

usuarios/templates/usuarios/listado_usuarios.html
						<!-- COMIENZO DEL SECTOR DE TARJETAS DE CANTIDAD-->
{% extends 'base.html' %}

{% block contenido1 %}


{% endblock %}

{% block contenido %}


<main class="container-body">
  <div id="contenido" class="pages-container-fluid pt-2 pb-2 pl-5 pr-5">
    <div class="col-12 col-xl-12 mb-4 align-items-stretch">
      <!-- Mensaje de bienvenida con el nombre del usuario o "invitado" si no está logueado -->
      <h4>Bienvenido,{% if user.is_authenticated %}{{ user.username }}{% else %}invitado{% endif %}!</h4>
      
      <!-- Información de la tarjeta -->
      <div class="card">
        
        <div class="card-body">
         
        	<div id="tabla" class="row">

				<div _ngcontent-c4="" class="col-12 col-xl-12 mb-4 align-items-stretch">
					<div _ngcontent-c4="" class="card h-100 border-0 rounded-0">
						<div _ngcontent-c4="" class="card-title mb-1 p-3 d-flex">
							<h5 class="card-header">LISTADO DE usuarios </h5> 
							<a _ngcontent-c4="" class="btn ml-auto p-0 text-lightning">
								<i _ngcontent-c4="" class="fas fa-ellipsis-h"></i>
							</a>
						</div>
						<div _ngcontent-c4="" class="card-body">
							<div _ngcontent-c4="" class="table-responsive-md">
								<div _ngcontent-c4="" class="table-responsive">
									<table _ngcontent-c4="" class="table ">
										<thead _ngcontent-c4="">
											<tr _ngcontent-c4="">
												
												<th _ngcontent-c4="" style="width:10%;">ID</th>
												<th _ngcontent-c4="" style="width:20%;">NOMBRE</th>
												<th _ngcontent-c4="" class="actions" style="width:5%;"></th>
												<th _ngcontent-c4="" class="actions" style="width:5%;"></th>
												
											</tr>
										</thead>
										<tbody _ngcontent-c4="" class="no-border-x">
											{% for p in usuarios%} 
													<tr _ngcontent-c4="">
														<td _ngcontent-c4="">{{p.id}}</td>
														<td _ngcontent-c4="" class="number">{{ p.username }}</td>
														<td>
														 {% if p.is_active %}
															<td _ngcontent-c4="" class="actions">
															<a href="{% url 'usuarios:activar_usuario' p.id %}" type="button" class="btn btn-danger btn-sm">Desactivar</a></td>
														{% else %}
															<td _ngcontent-c4="" class="actions">
															<a href="{% url 'usuarios:activar_usuario' p.id %}" type="button" class="btn btn-danger btn-sm">Activar</a></td>
														{% endif %}
														
														<td _ngcontent-c4="" class="actions">
															<a href="{% url 'usuarios:editar_perfil' p.id %}" type="button" class="btn btn-danger btn-sm">EDITAR</a>
														</td>
														<td _ngcontent-c4="" class="actions">
															<a href="{% url 'usuarios:eliminar_usuario' p.id %}" type="button" class="btn btn-danger btn-sm">ELIMINAR</a>
														</td>
														<td _ngcontent-c4="" class="actions">
															<a href="{% url 'usuarios:movimiento_por_usuario' p.id %}" type="button" class="btn btn-danger btn-sm">MOVIMIENTOS</a>
														</td>
														</td>


														
													</tr>
											{% endfor %} 
										</tbody>
									</table>
									
								</div>
							</div>
						</div>
					</div>
				</div>
			


			</div>

        </div>
      </div>
    </div>
  </div>
</main>
			

{% endblock %}